export const GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST";
export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_FAILIURE = "GET_ALL_JOBS_FAILIURE";

export const UPDATE_JOBS_REQUEST = "UPDATE_JOBS_REQUEST";
export const UPDATE_JOBS_SUCCESS = "UPDATE_JOBS_SUCCESS";
export const UPDATE_JOBS_FAILIURE = "UPDATE_JOBS_FAILIURE";